targets:
  $default:
    builders:
      # Don't clean up codelab examples, they need to be served.
      build_web_compilers:dart_source_cleanup:
        generate_for:
          exclude:
            - web/example/codelabs/**.dart

      build_web_compilers|entrypoint:
        # Don't compile codelab examples.
        generate_for:
          exclude:
          - web/example/codelabs/**.dart
        options:
          dart2js_args:
          - --minify
          - --fast-startup
          - -DPRE_NULL_SAFETY_SERVER_URL=https://v1.api.dartpad.dev/
          - -DNULL_SAFETY_SERVER_URL=https://nullsafety.api.dartpad.dev/

      json_serializable:
        # Ignore codelab samples.
        generate_for:
          exclude:
          - web/example/codelabs/**.dart
